### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by keramat-farid** [imhmdrz/Guardian_news_android#4]
You can define only one function with parameters and use that to pass different values

https://github.com/imhmdrz/Guardian_news_android/blob/12be538b0b6ed04df9b1ef1f806b69de4d8e02a0/app/src/main/java/com/example/myproj/loadDataFromInternet/GuardianApiService.kt#L8

**Comment by imhmdrz** [comment]
Solved with @Querry Annotation
