### ISSUE TITLE
ApplicationViewModel usage

### ISSUE THREAD

**Issue by keramat-farid** [imhmdrz/Guardian_news_android#6]
You can use `ViewModel` instead of `AndroidViewModel`

https://github.com/imhmdrz/Guardian_news_android/blob/12be538b0b6ed04df9b1ef1f806b69de4d8e02a0/app/src/main/java/com/example/myproj/fragmentGuardian/GuardianViewModel.kt#L12

**Comment by imhmdrz** [comment]
solved
